eb:
  base:
    file-upload:
      dir: /tmp/cem



---
spring:
  config:
    activate:
      on-profile: suyh


eb:
  base:
    token-seconds: 36000
    captcha:
      two-factor-auth-enabled: false
    file-upload:
      dir: D:\tmp\cem


---
spring:
  config:
    activate:
      on-profile: suyh_mac


eb:
  base:
    token-seconds: 36000
    captcha:
      two-factor-auth-enabled: false
    file-upload:
      dir: /tmp/cem



---
spring:
  config:
    activate:
      on-profile: suyh_dev

eb:
  base:
    token-seconds: 36000
    captcha:
      two-factor-auth-enabled: false


