spring:
  config:
    import:
      - application-base.yaml
      - application-datasource.yaml
      - application-flyway.yaml
      - application-jackson.yaml
      - application-knife4j.yaml
      - application-log.yaml
      - application-message_source.yaml
      - application-mq.yaml
      - application-mybatis.yaml
      - application-redis.yaml
      - application-spring.yaml
      - application-web.yaml






