spring:
  datasource:
    dynamic:
      enabled: true
      strict: true
      primary: "cds-mysql"

---
spring:
  config:
    activate:
      on-profile: suyh,suyh_mac

  datasource:
    hikari:
      cds-mysql:
        jdbc-url: jdbc:mysql://isuyh.com:3306/study_vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: study_vue
        password: study_vue
        driver-class-name: com.mysql.cj.jdbc.Driver









