spring:
  main:
    # 对于有些时候我们不想启用web 服务，而只想使用spring-boot 时，可以禁用web 功能。
    web-application-type: servlet

server:
  servlet:
    context-path: /suyh
  port: 8015


---
spring:
  config:
    activate:
      on-profile: suyh,dev,suyh_dev,suyh_mac

server:
  error:
    # spring mvc 的默认异常处理，可以添加或者禁用一些返回值属性。
    include-binding-errors: always
    include-exception: true
    # message 取的是异常里面的描述字符串
    include-message: always
    include-stacktrace: on_param


